//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolRecord
    {
        public int SchooLID { get; set; }
        public string SchoolName { get; set; }
        public string SchoolAddress { get; set; }
        public int SchoolContact { get; set; }
        public int SchoolFax { get; set; }
        public string SchoolEmail { get; set; }
        public string SchoolWebsite { get; set; }
        public string SchoolBankName { get; set; }
        public string SchoolBankAddress { get; set; }
        public Nullable<int> SchoolBankAccount { get; set; }
    }
}
