//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolA
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDetail
    {
        public int StudentID { get; set; }
        public string StudentName { get; set; }
        public string StudentFname { get; set; }
        public string StudentMname { get; set; }
        public System.DateTime StudentDOB { get; set; }
        public int StudentSession { get; set; }
        public string StudentGender { get; set; }
        public string StudentNationality { get; set; }
        public string StudentFatherContact { get; set; }
        public System.DateTime StudentAdmdate { get; set; }
        public string StudentPreviousClass { get; set; }
        public string StudentPreviousSchool { get; set; }
        public string StudentTemporaryAdd { get; set; }
        public string StudentPermanentAdd { get; set; }
        public string StudentClass { get; set; }
        public string StudentSection { get; set; }
        public string StudentReligion { get; set; }
        public string StudentRemarks { get; set; }
    }
}
