//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherSubjectMap
    {
        public int TeacherSubID { get; set; }
        public string TeacherName { get; set; }
        public string SubjectAssigned { get; set; }
    }
}
