//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolA
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string UserFname { get; set; }
        public string UserEmail { get; set; }
        public int UserContact { get; set; }
        public string UserAddress { get; set; }
    }
}
