//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassFeeEntry
    {
        public int FeesID { get; set; }
        public string Class_Name { get; set; }
        public string Fees_Name { get; set; }
        public string FeeTerm { get; set; }
        public int Fee_Amount { get; set; }
    }
}
