//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMSEntities : DbContext
    {
        public SMSEntities()
            : base("name=SMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Add_Days_Detail> Add_Days_Details { get; set; }
        public virtual DbSet<Attendence> Attendences { get; set; }
        public virtual DbSet<ClassDetail> ClassDetails { get; set; }
        public virtual DbSet<ClassFeeEntry> ClassFeeEntries { get; set; }
        public virtual DbSet<ClassSectionMap> ClassSectionMaps { get; set; }
        public virtual DbSet<ExamType> ExamTypes { get; set; }
        public virtual DbSet<FeeReceiving> FeeReceivings { get; set; }
        public virtual DbSet<FeeType> FeeTypes { get; set; }
        public virtual DbSet<Result> Results { get; set; }
        public virtual DbSet<SchoolRecord> SchoolRecords { get; set; }
        public virtual DbSet<SectionDetail> SectionDetails { get; set; }
        public virtual DbSet<StockDetail> StockDetails { get; set; }
        public virtual DbSet<StudentDetail> StudentDetails { get; set; }
        public virtual DbSet<StudentFee> StudentFees { get; set; }
        public virtual DbSet<SubjectDetail> SubjectDetails { get; set; }
        public virtual DbSet<TeacherClassMap> TeacherClassMaps { get; set; }
        public virtual DbSet<TeacherRecord> TeacherRecords { get; set; }
        public virtual DbSet<TeacherSubjectMap> TeacherSubjectMaps { get; set; }
        public virtual DbSet<Term> Terms { get; set; }
        public virtual DbSet<TimeTable> TimeTables { get; set; }
        public virtual DbSet<Timing> Timings { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
    }
}
