//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolA
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockDetail
    {
        public int StockID { get; set; }
        public string StockName { get; set; }
        public string StockType { get; set; }
        public string SupplierName { get; set; }
        public int StockQtyPurchase { get; set; }
        public int StockQtyPresent { get; set; }
        public int StockQtySale { get; set; }
        public int StockPurPrice { get; set; }
        public int StockSalPrice { get; set; }
        public int StockTotPrice { get; set; }
        public System.DateTime StockDate { get; set; }
    }
}
