//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherRecord
    {
        public int TeacherID { get; set; }
        public string TeacherName { get; set; }
        public string TeacherFName { get; set; }
        public string TeacherCNIC { get; set; }
        public string TeacherContact { get; set; }
        public string TeacherTemporaryAddress { get; set; }
        public string TeacherPermanentAddress { get; set; }
        public string TeacherEducation { get; set; }
    }
}
